services:
  omeka:
    build:
      context: .
      args:
        OMEKA_S_VERSION: ${OMEKA_S_VERSION:-4.1.1}
        PHP_VERSION: ${PHP_VERSION:-8.2}
      target: prod
    restart: "no"
    env_file: ".env"
    ports:
      - ${OMEKA_S_EXPOSED_PORT:-8080}:80
    volumes:
      - omeka:/volume
    depends_on:
      - db

  db:
    image: mariadb:${MARIADB_VERSION:-11.4}
    restart: "no"
    volumes:
      - db:/var/lib/mysql
      - ./data/db-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: "no"
    ports:
      - ${PHPMYADMIN_EXPOSED_PORT:-8081}:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db

  solr:
    image: bitnami/solr:${SOLR_VERSION:-9}
    volumes:
      - solr:/bitnami
    environment:
      - SOLR_CORES=omeka

  mailpit:
    image: axllent/mailpit
    ports:
      - ${MAILPIT_EXPOSED_PORT:-8025}:8025

volumes:
  omeka:
  db:
  solr:
      