services:
  web:
    build:
      context: .
      args:
        OMEKA_S_VERSION: ${OMEKA_S_VERSION:-"4.1.1"}
        PHP_VERSION: ${PHP_VERSION:-"8.2"}
    restart: "no"
    env_file: ".env"
    ports:
      - ${EXPOSED_PORT_OMEKA:-8080}:80
    volumes:
      - ./omeka/files:/var/www/omeka-s/files
      - ./omeka/logs:/var/www/omeka-s/logs
      - ./omeka/modules:/var/www/omeka-s/modules
      - ./omeka/themes:/var/www/omeka-s/themes
      - ./omeka/config:/var/www/omeka-s/config
    depends_on:
      - db

  db:
    image: mariadb:${MARIADB_VERSION:-11.4}
    restart: "no"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/db-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: "no"
    ports:
      - ${EXPOSED_PORT_PHPMYADMIN:-8081}:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db

  solr:
    image: bitnami/solr:${SOLR_VERSION:-9}
    volumes:
      - ./data/solr:/var/solr
    environment:
      - SOLR_CORES=omeka