version: "3"

services:
  omeka-web:
    build:
      context: .
      args:
        OMEKA_S_VERSION : ${OMEKA_S_VERSION:-"4.1.1"}
        PHP_VERSION : ${PHP_VERSION:-"8.2"}
    restart: "no"
    env_file: ".env"
    
    ports:
      - 8080:80
    volumes:
      - ./omeka/files:/var/www/omeka-s/files
      - ./omeka/logs:/var/www/omeka-s/logs
      - ./omeka/modules:/var/www/omeka-s/modules
      - ./omeka/themes:/var/www/omeka-s/themes
    depends_on:
      - omeka-db

  omeka-db:
    image: mariadb:10.6
    restart: "no"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  omeka-db-admin:
    image: phpmyadmin/phpmyadmin:latest
    restart: "no"
    ports:
      - 8081:80
    environment:
      - PMA_HOST=omeka-db
    depends_on:
      - omeka-db

  solr:
    image: bitnami/solr:9
    ports:
     - "8983:8983"
    volumes:
      - ./data/solr:/var/solr
    environment:
      - SOLR_CORES=omeka